# Generated by Django 3.1.5 on 2021-02-01 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainEvol',
            fields=[
                ('id_chain', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'chain_evol',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id_pokemon', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('hp_base', models.IntegerField()),
                ('attack_base', models.IntegerField()),
                ('attack_sp_base', models.IntegerField()),
                ('defense_base', models.IntegerField()),
                ('defense_sp_base', models.IntegerField()),
                ('speed_base', models.IntegerField()),
                ('chain_evo_rel', models.ForeignKey(db_column='chain_evol_rel', on_delete=django.db.models.deletion.PROTECT, to='pokedex.chainevol')),
            ],
            options={
                'db_table': 'pokemon',
                'managed': True,
            },
        ),
    ]
