# Generated by Django 3.1.5 on 2021-02-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='chain_evo_rel',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='chain_evol_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChainEvol',
        ),
    ]
